In [4993]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import cdist
df = pd.read_excel('/Users/arthjani/Downloads/Ionosphere/Ionosphere_AE_1.xlsx', header=None)
# nan_values = df.isnull().any()
# print(nan_values)
## drroping the column
# df=df[df.columns[df.isna().any()]]
## dropping row
null_data = df[df.isnull().any(axis=1)]
# print(null_data)
data_top=null_data.index
index=[]
for i in data_top:
    index.append(i)
print(index)
df=cdist(df,df,'euclid')
df=pd.DataFrame(df)
# print(df.to_string())
#similarity dataset
#df


[0, 6, 15, 17, 42, 58, 120, 146, 168, 190, 223, 287]


In [4994]:
#converting into a numpy array and fixing the threshold
a= np.array(df)
med = 0.785
print(med)

0.785


In [4995]:
#keeping only values above threshold and making others as 0.
similarity_thres = []
for i in a:
    f1=[]
    for k in i:
        if(k==1):
            f1.append(0)
        elif(k>=med):
            f1.append(1)
        else:
            f1.append(0)
    similarity_thres.append(f1)

In [4996]:
#printing the boolean matrix
# similarity_thres

In [4997]:
#creating a new dataframe using the boolean matrix
new_df = pd.DataFrame(similarity_thres)

In [4998]:
#creating an index column to get the label in the desired format.
new_df['DOC'] = (new_df.index)
new_df['X']= "X"
new_df['DOC2'] = new_df['X']+new_df['DOC'].astype(str)
del new_df['DOC'],new_df['X']

In [4999]:
# #plotting the network 
# import networkx as nx
# import matplotlib.pyplot as plt
# stacked = new_df.set_index(['DOC2']).stack()
# stacked = stacked[stacked==1]
# edges = stacked.index.tolist()
# #print(il1)
# #edges
# G = nx.Graph(edges)
# Gp = nx.bipartite.project(G,new_df.set_index('DOC2').columns)
# Gp.edges()
# #pos = {node:[0, i] for i,node in enumerate(il1['DOC2'])}
# #pos.update({node:[1, i] for i,node in enumerate(il1['level_1'])})
# nx.draw(G, with_labels=True)
# #for p in pos:  # raise text positions
#  #   pos[p][1] += .25
# #nx.draw_networkx_labels(G,pos=pos)

# plt.show()

In [5000]:
##Reading the original dataset and performing the same to create labels and reindex.
dataset = pd.read_excel('/Users/arthjani/Downloads/Ionosphere/Ionosphere_AE_1.xlsx', header=None)
dataset.index = dataset.index+1
dataset['DOC'] = (dataset.index)
dataset['X']= "X"
dataset['index'] = dataset['X']+dataset['DOC'].astype(str)
del dataset['DOC'],dataset['X']
print(dataset)

     0  1        2        3        4        5        6        7        8  \
1    1  0  0.99539 -0.05889  0.85243  0.02306      NaN -0.37708      NaN   
2    1  0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
3    1  0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
4    1  0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
5    1  0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..  .. ..      ...      ...      ...      ...      ...      ...      ...   
347  1  0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
348  1  0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
349  1  0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
350  1  0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
351  1  0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

           9  ...       25       26       27       28       29       30  \
1    0.03760

In [5001]:
#splitting the null values and creating a new dataframe using the similarity boolean matrix.
#dataset.set_index('index',inplace=True)
dataset
null_data = dataset[dataset.isnull().any(axis=1)]
similarity_bool = new_df.copy()
similarity_bool.set_index('DOC2',inplace=True)

In [5002]:
#Resetting the index and deleting the index column
similarity_bool.reset_index(inplace=True)
#del similarity_bool['index']

In [5003]:
#del similarity_bool['level_0']

In [5004]:
## Taking only values above threshold but instead of converting it into 0 & 1 , we are keeping the similarity score as such.
similarity_thres1 = []
for i in a:
    f1=[]
    for k in i:
        if(k==1):
            f1.append(0)
        elif(k>=med):
            f1.append(k)
        else:
            f1.append(0)
    similarity_thres1.append(f1)

In [5005]:
##sscore is a new dataframe with the above scores.
sscore = pd.DataFrame(similarity_thres1)
sscore.index = sscore.index+1
sscore['DOC'] = (sscore.index)
sscore['X']= "X"
sscore['DOC2'] = sscore['X']+sscore['DOC'].astype(str)
del sscore['DOC'],sscore['X']
# sscore.set_index('DOC2',inplace=True)
# print(sscore)

In [5006]:
#doing stacked to only take the values not equal to 0.0 and then unstacking it.
stacked1 = sscore.set_index(['DOC2']).stack()
#print(stacked1)
stacked1 = stacked1[stacked1 != 0.0]
# print(stacked1)
edges = stacked1.index.tolist()
# print(edges)
unstacked = stacked1.unstack()
# print(unstacked)

In [5007]:
#creating the incomplete_tuples and complete_tuples from the unstacked dataframe.
print(unstacked)
##To determine the P value
incomplete_tuples = unstacked.columns.to_list()
total_tuples = unstacked.index.to_list()
complete_tuples = list(set(total_tuples) - set(incomplete_tuples))
print(incomplete_tuples)
print(complete_tuples)

           2         3         4         5         7         8         9    \
DOC2                                                                         
X2    3.380033  4.454509  2.540531  2.783883  4.859196  3.472495  3.271473   
X3         NaN  4.671267  1.838508  3.129187  4.679506  1.695460  3.452336   
X4    4.671267       NaN  4.728259  3.853289  3.754628  5.587566  4.107967   
X5    1.838508  4.728259       NaN  2.721250  4.871717  2.013416  3.156991   
X6    3.129187  3.853289  2.721250       NaN  3.820612  3.923487  1.413085   
...        ...       ...       ...       ...       ...       ...       ...   
X347  1.326592  4.810247  2.989063  3.568336  4.773545  2.434970  3.843333   
X348  1.456198  4.853090  3.163051  3.818409  4.863369  2.531763  4.056160   
X349  1.391267  4.830586  3.093763  3.777344  4.812042  2.457184  4.020101   
X350  1.192104  4.781328  2.859164  3.662524  4.700995  2.162645  3.941659   
X351  1.026578  4.731419  2.679004  3.337854  4.651453  2.200013

In [5008]:
#creating a new column in unstacked to house the index values.
unstacked['indexed'] = unstacked.index
#filling the unstacked df for NaN
unstacked.fillna(0,inplace=True)
#del unstacked['index']

In [5009]:
#Keeping only complete neighbours for the incomplete tuples in this "inc_complete" dataframe.
inc_complete = unstacked[~unstacked['indexed'].isin(incomplete_tuples)]
print(inc_complete)
#inc_complete
#Keeping only incomplete neighbours for the incomplete tuples in this "inc_complete" dataframe.
inc_incomplete =unstacked[unstacked['indexed'].isin(incomplete_tuples)]
print(inc_incomplete)

             2         3         4         5         7         8         9  \
DOC2                                                                         
X2    3.380033  4.454509  2.540531  2.783883  4.859196  3.472495  3.271473   
X3    0.000000  4.671267  1.838508  3.129187  4.679506  1.695460  3.452336   
X4    4.671267  0.000000  4.728259  3.853289  3.754628  5.587566  4.107967   
X5    1.838508  4.728259  0.000000  2.721250  4.871717  2.013416  3.156991   
X6    3.129187  3.853289  2.721250  0.000000  3.820612  3.923487  1.413085   
...        ...       ...       ...       ...       ...       ...       ...   
X347  1.326592  4.810247  2.989063  3.568336  4.773545  2.434970  3.843333   
X348  1.456198  4.853090  3.163051  3.818409  4.863369  2.531763  4.056160   
X349  1.391267  4.830586  3.093763  3.777344  4.812042  2.457184  4.020101   
X350  1.192104  4.781328  2.859164  3.662524  4.700995  2.162645  3.941659   
X351  1.026578  4.731419  2.679004  3.337854  4.651453  2.200013

In [5010]:
#Function to get complete neighbours and their similarities in a dictionary
#iterating over the columns in inc_complete, retrieving the complete neighbours for each incomplete tuple and putting them in a dictionary.
def incomplete_connection_creator(list_1,dict_1):
  listed = []
  listed1= []
  inc_complete = list_1
  incomplete_tuples = dict_1
  for column in inc_complete:
    name = column
    #print(name)
    kailai = (list(inc_complete[inc_complete[column] != 0.0].indexed))
    kailai1 = (list(inc_complete[inc_complete[column] != 0.0][column]))
    #print(kailai)
    listed.append(kailai)
    listed1.append(kailai1)
  #print(listed)
  zipped = zip(incomplete_tuples,listed)
  zipped1 = zip(incomplete_tuples,listed1)
  dict_da = dict(zipped)
  dict_db = dict(zipped1)
  return dict_da,dict_db

In [5028]:
#Getting the complete neighbours and their similarity scores
data_dict,data_dict1 = incomplete_connection_creator(inc_complete,incomplete_tuples)
# print(data_dict,"\n",data_dict1)

{2: ['X2', 'X4', 'X5', 'X6', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X17', 'X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38', 'X39', 'X40', 'X41', 'X42', 'X44', 'X45', 'X46', 'X47', 'X48', 'X49', 'X50', 'X51', 'X52', 'X53', 'X54', 'X55', 'X56', 'X57', 'X58', 'X60', 'X61', 'X62', 'X63', 'X64', 'X65', 'X66', 'X67', 'X68', 'X69', 'X70', 'X71', 'X72', 'X73', 'X74', 'X75', 'X76', 'X77', 'X78', 'X79', 'X80', 'X81', 'X82', 'X83', 'X84', 'X85', 'X86', 'X87', 'X88', 'X89', 'X90', 'X91', 'X92', 'X93', 'X94', 'X95', 'X96', 'X97', 'X98', 'X99', 'X100', 'X101', 'X102', 'X103', 'X104', 'X105', 'X106', 'X107', 'X108', 'X109', 'X110', 'X111', 'X112', 'X113', 'X114', 'X115', 'X116', 'X117', 'X118', 'X119', 'X120', 'X122', 'X123', 'X124', 'X125', 'X126', 'X127', 'X128', 'X129', 'X130', 'X131', 'X132', 'X133', 'X134', 'X135', 'X136', 'X137', 'X138', 'X139', 'X140', 'X141', 'X142', 'X143', 'X144', 'X145

In [5012]:
##Calculating the p value for the final calculation of node weights.
import math
def p_value_calc(list_1,dict_1):
  incomplete_tuples = list_1
  data_dict = dict_1
  ##calculating the term (1/Xm)
  if len(incomplete_tuples) != 0:
    term = 1/(len(incomplete_tuples))
  else:
    term = 1
  ##Summing all the length of values present in the dictionary to get the total number of complete neighbours to the incomplete tuples.
  summing = sum(len(v) for v in data_dict.values())
  ##math.ceil to Round up to the next whole number for the product of summing and term.
  value_1 =math.ceil(term * summing)
  return value_1

In [5013]:
#P-value :
p_value = p_value_calc(incomplete_tuples,data_dict)
print(p_value)

331


In [5014]:
##Creating a dictionary to find out the number of similarity scores associated with each incomplete tuple. We get the length of the dictionary's values for a particular element.
def length_getter(list_a,dict_a):
  list_length = []
  incomplete_tuples = list_a
  data_dict1 = dict_a
  ## checking if element in incomplete_tuples
  for y in incomplete_tuples:
    ##for that element we check the similarity scores in data_dict1 dictionary
    for y in data_dict1:
      ##intializing total to 0
      total = 0
      #print("Element:",y)
      #referencing to fetch the similarity scores -> ex: data_dict1['X1']=[0.814,0.836]
      value_list = data_dict1[y]
      #print(value_list)
      ##Taking their length
      count = len(value_list)
      total += count
      ##appending individual length to a list
      list_length.append(total)
  #print(list_length)
  ##Creating the dictionary which contains the incomplete tuples and their associated value lengths.
  zipper=zip(incomplete_tuples,list_length)
  data_dict = dict(zipper)
  return data_dict

In [5015]:
data_dict2 = length_getter(incomplete_tuples,data_dict1)
# print(data_dict2)

In [5027]:
##Calculating the node weights and putting them in a dictionary function
def node_weight_calculator(dict_1,dict_2,tuple_1,value1):
  list_scores = [] 
  diction_1 = dict_1
  diction_2 = dict_2 
  tupled_1 = tuple_1 
  p_value = value1
  ## iterating over incomplete tuple  present in incomplete_tuples list.
  for ij in tupled_1:
    #calculating the length of each item in data_dict2
    length = (dict_2[ij])
    #if length is greater than 0 we calculate the similarity score, else we assign 0
    if length>0:
      multiply_list = []
      #iterate over the length so as to capture all the associate similarity pairs with each incomplete tuple.
      for i in range(length):
        sim_score = dict_1[ij][i]
        ##Calculating the part of node weight from the formula given in the paper.
        initial_calc = (1-sim_score)**(1/(p_value))
        ##appending to multiply_list the values of initial_calc
        multiply_list.append(initial_calc)
      #Multiplying all the initial_Calc associated with a element.
      weight_1 =np.prod(multiply_list)
      ##subtracting 1 from weight_1 as per formula and rounding it to three decimal places to get the final node weight.
      final_weight = np.round(1 - weight_1,3)
    else:
      #keeping node weight as 0 if there is no similarity
      final_weight = 0.0
    list_scores.append(final_weight)
  ##Creating the final dictionary which contains the incomplete tuple and its associated node weight.
  zipper_score = zip(tupled_1,list_scores)
  dict_output = dict(zipper_score)
  return dict_output

In [5017]:
##Initial Node weight calculator
dict_scores = node_weight_calculator(data_dict1,data_dict2,incomplete_tuples,p_value)
print("Initial Node weight beofre Imputation Order calc:\n",dict_scores)

Initial Node weight beofre Imputation Order calc:
 {2: (2.23-0.012j), 3: (4.915+0.26j), 4: (3.319+0.154j), 5: (3.261-0.086j), 7: (5.046+0.269j), 8: (3.445+0.023j), 9: (3.506+0.167j), 10: (3.868+0.082j), 11: (4.775+0.251j), 12: (3.063+0j), 13: (3.812+0.187j), 14: (2.675+0.016j), 16: (2.221-0.584j), 18: (2.679+0.112j), 19: (5.827+0.321j), 20: (2.671-0.048j), 21: (6.162+0.343j), 22: (1.98-0.307j), 23: (5.796+0.319j), 24: (2.298-0.124j), 25: (5.163+0.277j), 26: (3.996+0.199j), 27: (5.975+0.331j), 28: (4.381+0.225j), 29: (6.372+0.357j), 30: (3.31+0.066j), 31: (5.132+0.275j), 32: (2.873+0.036j), 33: (3.84+0.189j), 34: (3.247+0.15j), 35: (4.545+0.236j), 36: (2.4-0.686j), 37: (5.921+0.327j), 38: (2.155-0.512j), 39: (3.164+0.144j), 40: (3.481+0.071j), 41: (6.129+0.341j), 43: (5.261+0.283j), 44: (3.4+0.023j), 45: (5.243+0.282j), 46: (2.653-0.126j), 47: (4.41+0.227j), 48: (2.249-0.583j), 49: (4.709+0.247j), 50: (2.978+0.132j), 51: (5.501+0.299j), 52: (5.662+0.31j), 53: (6.507+0.366j), 54: (2.475-

In [5018]:
##Incomplete- Incomplete connections and similarities
data_dict_inc,data_dict_inc_1 = incomplete_connection_creator(inc_incomplete,incomplete_tuples)
print("Incomplete neighbours to incomplete tuples:\n",data_dict_inc)
print("Incomplete neighbours similarity Score:\n",data_dict_inc_1)

Incomplete neighbours to incomplete tuples:
 {2: [], 3: [], 4: [], 5: [], 7: [], 8: [], 9: [], 10: [], 11: [], 12: [], 13: [], 14: [], 16: [], 18: [], 19: [], 20: [], 21: [], 22: [], 23: [], 24: [], 25: [], 26: [], 27: [], 28: [], 29: [], 30: [], 31: [], 32: [], 33: [], 34: [], 35: [], 36: [], 37: [], 38: [], 39: [], 40: [], 41: [], 43: [], 44: [], 45: [], 46: [], 47: [], 48: [], 49: [], 50: [], 51: [], 52: [], 53: [], 54: [], 55: [], 56: [], 57: [], 59: [], 60: [], 61: [], 62: [], 63: [], 64: [], 65: [], 66: [], 67: [], 68: [], 69: [], 70: [], 71: [], 72: [], 73: [], 74: [], 75: [], 76: [], 77: [], 78: [], 79: [], 80: [], 81: [], 82: [], 83: [], 84: [], 85: [], 86: [], 87: [], 88: [], 89: [], 90: [], 91: [], 92: [], 93: [], 94: [], 95: [], 96: [], 97: [], 98: [], 99: [], 100: [], 101: [], 102: [], 103: [], 104: [], 105: [], 106: [], 107: [], 108: [], 109: [], 110: [], 111: [], 112: [], 113: [], 114: [], 115: [], 116: [], 117: [], 118: [], 119: [], 121: [], 122: [], 123: [], 124: [], 1

In [5019]:
## Calculating the Node Weight like we did previously for the values.
##Creating a dictionary to find out the number of similarity scores associated with each incomplete tuple. We get the length of the dictionary's values for a particular element.
data_dict_2 = length_getter(incomplete_tuples,data_dict_inc_1)
print("Length of incomplete neighbours:\n",data_dict_2)

##Appending the node weight we have already calculated for these nodes.
print("Node Weights:",dict_scores)
score_list = []
score_list_name = []
removed_item =[]
for element in incomplete_tuples:
  if data_dict_2[element] > 0:
    score_list_name.append(element)
    score_list.append(dict_scores[element])    
  else:
    print("Removed")
    removed_item.append(element)
zip_score_final = zip(score_list_name,score_list)
data_final_scores = dict(zip_score_final)
print("removed item",removed_item)
print("Node Weights input to Greedy Algorithm:\n",data_final_scores)

Length of incomplete neighbours:
 {2: 0, 3: 0, 4: 0, 5: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 16: 0, 18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0, 26: 0, 27: 0, 28: 0, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 43: 0, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 0, 50: 0, 51: 0, 52: 0, 53: 0, 54: 0, 55: 0, 56: 0, 57: 0, 59: 0, 60: 0, 61: 0, 62: 0, 63: 0, 64: 0, 65: 0, 66: 0, 67: 0, 68: 0, 69: 0, 70: 0, 71: 0, 72: 0, 73: 0, 74: 0, 75: 0, 76: 0, 77: 0, 78: 0, 79: 0, 80: 0, 81: 0, 82: 0, 83: 0, 84: 0, 85: 0, 86: 0, 87: 0, 88: 0, 89: 0, 90: 0, 91: 0, 92: 0, 93: 0, 94: 0, 95: 0, 96: 0, 97: 0, 98: 0, 99: 0, 100: 0, 101: 0, 102: 0, 103: 0, 104: 0, 105: 0, 106: 0, 107: 0, 108: 0, 109: 0, 110: 0, 111: 0, 112: 0, 113: 0, 114: 0, 115: 0, 116: 0, 117: 0, 118: 0, 119: 0, 121: 0, 122: 0, 123: 0, 124: 0, 125: 0, 126: 0, 127: 0, 128: 0, 129: 0, 130: 0, 131: 0, 132: 0, 133: 0, 134: 0, 135: 0, 136: 0, 137: 0, 138: 0, 139: 0, 140: 0, 1

In [5020]:
def incomplete_connection_creator1(list_1,dict_1):
  listed = []
  listed1= []
  inc_complete = list_1
  incomplete_tuples = dict_1
  #print(inc_complete)
  #print(incomplete_tuples)
  for column in inc_complete:
    for column in incomplete_tuples:
      name = column
      #print(name)
      kailai = (list(inc_complete[inc_complete[column] != 0.0].indexed))
      kailai1 = (list(inc_complete[inc_complete[column] != 0.0][column]))
      #print(kailai)
      listed.append(kailai)
      listed1.append(kailai1)
    #print("listed:",listed)
    zipped = zip(incomplete_tuples,listed)
    zipped1 = zip(incomplete_tuples,listed1)
    dict_da = dict(zipped)
    dict_db = dict(zipped1)
    return dict_da,dict_db

In [5026]:
'''
GREEDY ALGORITHM TO FIND THE IMPUTATION ORDER
STEP 1: Find Node with Largest Weight. Keep it as the starting point
STEP 2: Calculate the Filling Gain to make it a complete Neighbour.
STEP 3: If the imputed Node, contains any connections to incomplete tuples then update their node weights by considering the imputed node
        as a completed neighbour.
STEP 4: Repeat this process untill all the incomplete tuples are imputed.
'''

##STEP 1: Find Node with Largest Weight. Keep it as the starting point
#Getting the data_final_scores
incomplete_tuples_score = data_final_scores
print("Incomplete Tuple Scores Before Iteration:",incomplete_tuples_score)
#updated_incomplete_tuples = incomplete_tuples.copy()
updated_incomplete_tuples = score_list_name.copy()
updated_complete_tuples = complete_tuples.copy()
final_greedy_order = []
print("Node Weight for incomplete tuples stored in a new dictionary:",incomplete_tuples_score)
################################################################################################
##########################:
for i in range(len(incomplete_tuples_score)):  
  max_value = max(incomplete_tuples_score, key=incomplete_tuples_score.get)
  print("Node With the largest weight:",max_value)
  print("Node weight:",incomplete_tuples_score[max_value])
  
  ##Calculate the Filling Gain
  #print("X is:",data_dict_2[max_value])
  #print("Pairs are :",data_dict_inc[max_value])

  # data_dict_inc.pop('X6',None)
  # data_dict_2.pop('X6',None)
  # print(data_dict_2)
  # print(incomplete_tuples_score)
  if max_value in data_dict_2:
    list_score_holder = []
    final_gain_score_holder = []  
    for i in range(data_dict_2[max_value]):
      try:
       w_label = data_dict_inc[max_value][i]
       w_score = incomplete_tuples_score[w_label]
       print("Connected pair and score :",w_label,w_score)
       list_score_holder.append(w_score)
       #print(data_dict_inc_1[max_value][i])
       #print(p_value)
       w_difference = np.round((incomplete_tuples_score[max_value] - list_score_holder[i]),3)
       #print(data_dict_inc_1[max_value][i])
       w_second_part =np.round((1-data_dict_inc_1[max_value][i])**(1/p_value),3)
       gain = np.round(((w_difference)*(1-w_second_part)),3)
       #print(w_difference)
       #print(w_second_part)
       #print("Gain is :",gain)
       final_gain_score_holder.append(gain)
       #print("Final Gain calculated:",final_gain_score_holder)
      except Exception as e:
       print(e)

    gain_for_element = sum(final_gain_score_holder)
    print("Gain For incomplete tuple:",gain_for_element )
    updated_incomplete_tuples.remove(max_value)
    updated_complete_tuples.append(max_value)
    print("Updated_incomplete_tuples",updated_incomplete_tuples)
    print("Updated complete tuples",updated_complete_tuples)
    inc_complete_updated = unstacked[~unstacked['indexed'].isin(updated_incomplete_tuples)]
    data_dict_upd_1,data_dict_upd_2 = incomplete_connection_creator1(inc_complete_updated,updated_incomplete_tuples)
    upd_p_value = p_value_calc(updated_incomplete_tuples,data_dict_upd_1)
    data_dict_upd = length_getter(updated_incomplete_tuples,data_dict_upd_2)
    print("data_dict_upd_2:-",data_dict_upd_2)
    print("data_dict_upd_1:",data_dict_upd_1)
    print(max_value)
    new_dict = { k : v for k,v in data_dict_upd_1.items() if max_value in v}
    new_dict_scores = []
    new_dict_key = []
    for key,value in new_dict.items():
      new_value = data_dict_upd_2[key]
      new_dict_scores.append(new_value)
      new_key = key
      new_dict_key.append(key)
    new_zipped = zip(new_dict_key,new_dict_scores)
    new_dict_input = dict(new_zipped)
    print(new_dict_input)
    dict_scores_upd = node_weight_calculator(new_dict_input,data_dict_upd,new_dict_key,p_value)
    print("Updated Node weight before Imputation Order calc:\n",dict_scores_upd)
    dict_scores_upd.update({max_value:0.0})
    final_greedy_order.append(max_value)
    print("Appended:",dict_scores_upd)
    incomplete_tuples_score.update(dict_scores_upd)
    print("Updated Incomplete Tuples scores before proceeding to next iter",incomplete_tuples_score)
    print("----------------------------------------------------------------------------------------------------------------------")
print("Final Greedy Imputation order is",final_greedy_order)

##Creating the final order for feeding to the KNN
final_order = removed_item+final_greedy_order
print("final_order",final_order)
final_greedy_impute = []
# for a in final_order:
#   str_name = str(a)
#   strip_name = str_name[1:]
#   final_greedy_impute.append(int(strip_name))
data_top= np.array(data_top)
data_top=data_top+1
final_greedy_impute= data_top
# print(data_top)
print(final_greedy_impute)

Incomplete Tuple Scores Before Iteration: {}
Node Weight for incomplete tuples stored in a new dictionary: {}
Final Greedy Imputation order is []
final_order [2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 191, 192, 193, 194, 195, 196, 197, 198, 1

In [5022]:
############################
#KNN Modelling Approach
dataset_1 = dataset.copy()
# dataset_1 
dataset_1.set_index('index',inplace=True)
dataset_1

0   1        2        3        4        5        6        7        8   \
index                                                                          
X1      1   0  0.99539 -0.05889  0.85243  0.02306      NaN -0.37708      NaN   
X2      1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
X3      1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
X4      1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
X5      1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
...    ..  ..      ...      ...      ...      ...      ...      ...      ...   
X347    1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
X348    1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
X349    1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
X350    1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
X351    1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

            9   ...       24       25       26       27       28       29  \
index           ...                                                         
X1     0.03760  ...      NaN -0.51171  0.41078 -0.46168  0.21266 -0.34090   
X2    -0.04549  ... -0.20332 -0.26569 -0.20468 -0.18401 -0.19040 -0.11593   
X3     0.01198  ...  0.57528 -0.40220  0.58984 -0.22145  0.43100 -0.17365   
X4     0.00000  ...  1.00000  0.90695  0.51613  1.00000  1.00000 -0.20099   
X5    -0.16399  ...  0.03286 -0.65158  0.13290 -0.53206  0.02431 -0.62197   
...        ...  ...      ...      ...      ...      ...      ...      ...   
X347  -0.04622  ...  0.95378 -0.04202  0.83479  0.00123  1.00000  0.12815   
X348   0.01606  ...  0.94520  0.01361  0.93522  0.04925  0.93159  0.08168   
X349   0.02446  ...  0.93988  0.03193  0.92489  0.02542  0.92120  0.02242   
X350   0.00110  ...  0.91050 -0.02099  0.89147 -0.07760  0.82983 -0.17238   
X351  -0.09139  ...  0.86467 -0.15114  0.81147 -0.04822  0.78207 -0.00703   

            30       31       32       33  
index                                      
X1     0.42267 -0.54487      NaN -0.45300  
X2    -0.16626 -0.06288 -0.13738 -0.02447  
X3     0.60436 -0.24180  0.56045 -0.38238  
X4     0.25682  1.00000 -0.32382  1.00000  
X5    -0.05707 -0.59573 -0.04608 -0.65697  
...        ...      ...      ...      ...  
X347   0.86660 -0.10714  0.90546 -0.04307  
X348   0.94066 -0.00035  0.91483  0.04712  
X349   0.92459  0.00442  0.92697 -0.00577  
X350   0.96022 -0.03757  0.87403 -0.16243  
X351   0.75747 -0.06678  0.85764 -0.06151  

[351 rows x 34 columns]

In [5023]:
##Order Imputed Sequential KNN 
##Creating a null empty array equal to the dataset size
dataset_array = dataset_1.to_numpy()
print("Dataset Converted into a Numpy Array:\n",dataset_array)
#imputed_data = np.zeros([len(dataset_1),len(dataset_1.columns)])
imputed_data = np.zeros_like(dataset_array)
print("\nZeroes Array\n",imputed_data)
#Creating Empty lists 
complete = []
incompleted = []
missing =[]
com_ind=[]
incomp_ind=[]
##Taking the rows and cols of the input dataset for iteration purpose
[rows,cols] = dataset_array.shape
print("\nNo of Rows are",rows)
print("No of Cols are",cols)
##iterating through the number of rows
for i in range(len(dataset_array)):
  a = dataset_array[i]
  #print("Row is ",a)
  nan_checker = np.sum(np.sum(a, axis=0))
  #print("Sum of Row is",nan_checker)
  if math.isnan(nan_checker) :
    #print("Spotted Nan Value - ",nan_checker)
    incompleted.append(a)
    incomp_ind.append(i+1)
    #print("Non Sum of non numbers",np.nansum(np.nansum(a, axis=0)))
  else:
    complete.append(a)
    com_ind.append(i+1)
zipped_com = zip(com_ind,complete)
dict_complete = dict(zipped_com)
##Ordering the list as per imputation order generated from Greedy
zipped_incom = zip(incomp_ind,incompleted)
dict_incompleted = dict(zipped_incom)
print(dict_incompleted)
sorted_incomplete =[(v,dict_incompleted[v]) for v in final_greedy_impute]
print(sorted_incomplete)
incom_ind = []
incomplete = []
for header in range(len(sorted_incomplete)):
  header_app = sorted_incomplete[header][0]
  value_app = sorted_incomplete[header][1]
  incom_ind.append(header_app)
  incomplete.append(value_app)
print(incom_ind)
print(incomplete)
incom_ind_1 = sorted_incomplete[0][0]
print(incom_ind_1)
for i in com_ind:
  imputed_data[i-1] = dict_complete[i]
print("Imputed Data After Filling the Complete Rows:\n",imputed_data)
print("Incomplete Rows in the Array\n",incomplete)

for k in incomplete:
  #print(k)
  dist = []
  cgen = len(complete)
  for j in range(cgen):
    #print(k)
    #print("j",j)
    #print(complete[j])
    d = np.nansum(np.power(([k]-complete[j]),2))
    dist.append(d)
  print("Distance Before Sort:",dist)  
  position=[]
  for l in range(len(dist)):
    position.append(l)
  zipped_pos = zip(position,dist)
  dict_pos = dict(zipped_pos)
  #print(dict_pos)
  from operator import itemgetter  
  dict_pos_sorted =  sorted(dict_pos.items(), key = itemgetter(1), reverse = False)
  print("Sorted Dictionary",dict_pos_sorted)
  K = 5
  cluster_dictionary = dict_pos_sorted[:5]
  print("K Cluster Dictionary",cluster_dictionary)
  k_dist = []
  k_weight = []
  k_final_weight = []
  for d,s in cluster_dictionary:
    k_dist.append(s)
  print("Retrieved K Distances",k_dist)
  #total_list_sum = sum(1/((k_dist)))
  #print(total_list_sum)
  for h in range(len(k_dist)):
    #weight = np.true_divide((1/k_dist[h]),)
    individual_weight = ((1/k_dist[h]))
    k_weight.append(individual_weight)
  for u in k_weight:
    final_weight = np.true_divide(u,sum(k_weight))
    k_final_weight.append(final_weight)
  #print("K Weight:",k_weight)   
  print("Final_Weight:",k_final_weight)
  #print(complete)
  for a in range(np.size(dataset_array,1)):
      complete_values_list =[] 
      column_value = k[a]
      if math.isnan(column_value):
        for o,p in cluster_dictionary:
          complete_value = complete[o][a]
          complete_values_list.append(complete_value)
        #print("Complete_value",complete_values_list)
        imputed_final_value = round(sum(f * e for f, e in zip(complete_values_list,k_final_weight)),3)
        print("-----------------------------------------------------------------------------------------")
        print("Final Imputed value:",imputed_final_value) 
        print("-----------------------------------------------------------------------------------------")
        k[a] = imputed_final_value
  complete.append(k)
incomplete_dataframe = pd.DataFrame(incomplete)
incomplete_dataframe['ind'] = incom_ind
incomplete_dataframe.set_index('ind',inplace=True)
imputed_data_frame = pd.DataFrame(imputed_data)
imputed_data_frame.index = imputed_data_frame.index+1
final_imputed_df = incomplete_dataframe.combine_first(imputed_data_frame)
final_imputed_df.columns = dataset_1.columns
print("------------------------------------------------------------------------")
print("------------------------------------------------------------------------")
print("Final Imputed Dataset:\n", final_imputed_df)
print("------------------------------------------------------------------------")
print("------------------------------------------------------------------------")
print("Completed")
final_imputed_df.to_excel('/Users/arthjani/Downloads/imputed/Ionosphere/imputed_Ionosphere_AE_1.xlsx')

Dataset Converted into a Numpy Array:
 [[ 1.       0.       0.99539 ... -0.54487      nan -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]

Zeroes Array
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

No of Rows are 351
No of Cols are 34
{1: array([ 1.     ,  0.     ,  0.99539, -0.05889,  0.85243,  0.02306,
            nan, -0.37708,      nan,  0.0376 ,  0.85243, -0.17755,
            nan, -0.44945,  0.60536, -0.38223,      nan, -0.38542,
            nan, -0.32192,      nan, -0.29674,  0.36946, -0.47357,
            nan, -0.51171,  0.41078, -0.46168,  0.21266, -0.3409 ,
        0.42267, -0.54487,      nan, -0.4

In [5025]:
# # NRMS calculation
# import numpy
# final_imputed_data=pd.read_excel('/Users/arthjani/Downloads/imputed/Ionosphere/imputed_Ionosphere_AE_1.xlsx')
# # final_imputed_data.drop(labels=" ", axis=1,inplace=True)
# # del final_imputed_data[final_imputed_data.columns[0]]
# # final_imputed_data.to_excel('/Users/arthjani/Downloads/imputed/imputed_iris_AE_1.xlsx')
# original_data=pd.read_excel('/Users/arthjani/Downloads/Ionosphere.xlsx')
# nrms_numerator = np.linalg.norm(final_imputed_data)
# # print(nrms_numerator)
# nrms_denomerator= np.linalg.norm(original_data)
# # print(nrms_denomerator)
# nrms_value=nrms_numerator/nrms_denomerator
# print(nrms_value)
# # nrms_value.append(nrms)

0.9292858895016269
